### ISSUE TITLE
Waterbody shapefile lacks COMIDs

### ISSUE THREAD

**Issue by rmfricke** [woodsp/angling#1]
Need to replace the Waterbody.shp with new raw data source containing COMID field.

**Comment by rmfricke** [comment]
We're going to use the national shapefile instead: [http://prd-tnm.s3-website-us-west-2.amazonaws.com/?prefix=StagedProducts/Hydrography/NHD/National/HighResolution/GDB/]

**Comment by woodsp** [comment]
Scratch that, we're building this workflow around NHD v2.1 Waterbody table.  NHD v2.1 differs from NHD v2.0 by using "PERMANENT_IDENTIFIER" instead of "COMID".  Lakes that existed in v2.0 kept their original (COMID) ID values.  This will allow us to join LakeCat data, through LakeCat's COMID field.

NHD 2.1 is available as shapefiles by state or as a national geodatabase.  We'll probably loop through the state-level shapefiles, which are at http://prd-tnm.s3-website-us-west-2.amazonaws.com/?prefix=StagedProducts/Hydrography/NHD/State/HighResolution/Shape/

**Comment by rmfricke** [comment]
This issue is resolved, see woodsp comment above.
